Servo driver
matrix-io/matrix-creator-malos pull request #16
Opened 2016-10-10 23:50 UTC by hpsaturn

First version for basic handler of IO Servo motors on MALOS

2016-10-11 01:11 UTC, brianofrokk3r reviewed
Can you update the available MALOS methods in the comments at the top of this JS script?

2016-10-11 01:18 UTC, arhuaco requested changes
Hi Antonio, sending comments. This PR depends on the PR for the protos.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +#define INPUT 0
Hi Antonio.

We've following this guide: https://google.github.io/styleguide/cppguide.html#Constant_Names

So you can do:

// Input channel?
const int kInput = 0;
// Pwm selector
const int kPwm = 1;
// Clock frequency as needed by chip X
const int kClockFrequency = 200000000;

Notice how this is done below for kServoDriverDebugEnabled.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +
Nitpick: Extra space.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  int16_t pin      = (int16_t)servo.pin();
Please run clang-format. It is useful because people can run clang-format later on the directory and no spurious changed (that have to do with indentation) will be generated. Indentation is a problem better left to the computer :-)

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  gpio.SetFunction(pin, PWM);    // pin 4, PWM output */
You don't need the /\* here nor in the comment below.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  gpio.SetPrescaler(bank, 0x5);  // set prescaler bank 0 */
Nit: Perhaps add 0x5 as another constant?

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  int16_t duty_counter = 0;
You should declare int16_t duty_counter right below, where the variable is being initialized.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  duty_counter = (37.7 * servo.angle()) + 1800;
What is the 1800? In case it is where the servo start frequency, isn't it hardware dependent? With RC planes you usually have to calibrate.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  std::cout << " Servo angle  : " << servo.angle() << "\t";
Do you need to print? This might impact performance of the driver. In case you do want to print you should replace the "\n" below with std::endl.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +
Extra \n

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.h
> + private:
You can delete the private section as isValidLircSymbol is form the other .h.

2016-10-11 01:18 UTC, arhuaco commented on src/js_test/test_servo.js
> +var creator_everloop_base_port = 20013 + 32 // port for Everloop driver.
It says "Port for everloop driver".

2016-10-11 01:18 UTC, arhuaco commented on src/js_test/test_servo.js
> +configSocket.connect('tcp://' + creator_ip + ':' + creator_everloop_base_port /* config */)
creator_everloop_base_port ...

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  matrix_hal::WishboneBus bus;
Do you need to do the wishbone initialization here?

See how the Everloop driver gets a reference to the SPI bus. You're doing it here for every ProcessConfig call and you could do it only once.

You can have "matrix_hal::GPIOControl *" in the .h as the everloop driver does.

You can also check the base class MalosWishboneBase in malos_wishbone_base.h. You need to define

    void SetupWishboneBus(matrix_hal::WishboneBus*) {}

as the everloop driver does.

You can follow the calls to SetupWishboneBus in malos.cpp.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +  uint16_t period_counter = (0.02 * CLK_FRQ) / ((1 << 5) * 2);
Nit: If it is useful a small comment about this formula would help.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.h
> +  // Read configuration of IR command (from the outside world).
The comment says "IR command". This comment no longer holds.

2016-10-11 01:18 UTC, arhuaco commented on src/driver_servo.cpp
> +#include "./src/driver.pb.h"
Please send a PR for the protocol buffers.

2016-10-11 01:18 UTC, arhuaco commented on src/malos.cpp
> +  if (!driver_servo.Init(kBasePort + 4 * 8 + 1, kUnsecureBindScope)) {
After this line is where you can do:
  driver_servo.SetupWishboneBus(wishbone_bus);
(Following the comments given before).

2016-10-11 14:01 UTC, hpsaturn commented on src/driver_servo.cpp
> +#include "./src/driver.pb.h"
sorry I was missing this. Done.

2016-10-24 21:06 UTC, hpsaturn commented on src/driver_servo.cpp
> +  gpio.SetFunction(pin, PWM);    // pin 4, PWM output */
copy paste for another code, sorry.

2016-10-24 21:11 UTC, hpsaturn commented on src/driver_servo.cpp
> +  duty_counter = (37.7 * servo.angle()) + 1800;
Is a task or research on the future because some libraries not need calibration, for example Arduino library with most servos.

2016-10-24 21:40 UTC, arhuaco requested changes
Antonio, thamks for the chantges. This is almost good to go. Minor changes and we can merge this.

2016-10-24 21:40 UTC, arhuaco commented on src/driver_servo.h
> +  // Read configuration of IR command (from the outside world).
Pending...

2016-10-24 21:40 UTC, arhuaco commented on src/driver_servo.h
> + private:
Pending

2016-10-24 21:40 UTC, arhuaco commented on src/js_test/test_servo.js
> +configSocket.connect('tcp://' + creator_ip + ':' + creator_everloop_base_port /* config */)
Pending...

2016-10-24 21:40 UTC, arhuaco commented on src/driver_servo.h
> +  // Everloop writer.
Not everloop driver.

2016-10-24 21:40 UTC, arhuaco commented on src/driver_servo.h
> +#include <string>
Nit: Is <string> used in this file?

2016-10-24 22:10 UTC, arhuaco approved these changes
Good to go.

2016-10-24 22:44 UTC, merged

2016-10-25 04:42 UTC, arhuaco commented
Antonio, this is not compiling for me! I think you forgot to send the PR for the protocol buffer changes (I guess ServoParams is there). Opening issue, please take a look.

2016-10-25 04:44 UTC, arhuaco commented
I also missed a few details in the review. I'll send a patch once the build is fixed.